### ISSUE TITLE
Unhandled Exception: DioError [DioErrorType.DEFAULT]: Exception: Already connected

### ISSUE THREAD

**Issue by natchoz** [GetStream/stream-chat-flutter#237] opened 2021-01-27 15:55 UTC
During chatting in the chat room, when token is expired, I have refresh token by using tokenProvider but I got this error and I cannot get any messages from others. 
Any ideas? 
Thank you very much

`I/flutter (12258): (2021-01-27 22:50:50.932579) ℹ️ 📡 set user
I/flutter (12258): (2021-01-27 22:50:50.972959) ℹ️ 📡 connecting
I/flutter (12258): (2021-01-27 22:50:50.973450) ⚠️ 📡 Already connected
E/flutter (12258): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: Exception: Already connected
E/flutter (12258): #0      Client.post (package:stream_chat/src/client.dart:811:7)
E/flutter (12258): <asynchronous suspension>
E/flutter (12258): #1      Channel.markRead (package:stream_chat/src/api/channel.dart:434:36)
E/flutter (12258): #2      _MessageListViewState.initState.<anonymous closure> (package:stream_chat_flutter/src/message_list_view.dart:556:35)
E/flutter (12258): #3      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (12258): #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (12258): #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (12258): #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (12258): #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (12258): #8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
E/flutter (12258): #9      _MapStream._handleData (dart:async/stream_pipe.dart:224:10)
E/flutter (12258): #10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
E/flutter (12258): #11     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (12258): #12     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (12258): #13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (12258): #14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (12258): #15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (12258): #16     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:127:11)
E/flutter (12258): #17     _MapStream._handleData (dart:async/stream_pipe.dart:224:10)
E/flutter (12258): #18     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:157:13)
E/flutter (12258): #19     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (12258): #20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (12258): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (12258): #22     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (12258): #23     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:285:7)
E/flutter (12258): #24     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:385:25)
E/flutter (12258): #25     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
E/flutter (12258): #26     _StartWithStreamSink.add (package:rxdart/src/transformers/start_with.dart:16:10)
E/flutter (12258): #27     forwardStream.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:34:49)
E/flutter (12258): #28     forwardStream.runCatching (package:rxdart/src/utils/forwarding_stream.dart:24:12)
E/flutter (12258): #29     forwardStream.<anonymous closure>.<anonymous closure> (package:rxdart/src/utils/forwarding_stream.dart:34:28)
E/flutter (12258): #30     _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (12258): #31     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (12258): #32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (12258): #33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)
E/flutter (12258): #34     _DelayedData.perform (dart:async/stream_impl.dart:611:14)
E/flutter (12258): #35     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)
E/flutter (12258): #36     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:687:7)
E/flutter (12258): #37     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (12258): #38     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (12258): #39     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (12258): #40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (12258): #41     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (12258): #42     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (12258): #43     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (12258): #44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (12258): #45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (12258): #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (12258): 
E/flutter (12258): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Exception: Already connected
E/flutter (12258): #0      Client.connect (package:stream_chat/src/client.dart:456:7)
E/flutter (12258): #1      Client.setUser (package:stream_chat/src/client.dart:382:12)
E/flutter (12258): <asynchronous suspension>
E/flutter (12258): #2      Client._tokenExpiredInterceptor (package:stream_chat/src/client.dart:291:15)
E/flutter (12258): <asynchronous suspension>
E/flutter (12258): #3      InterceptorsWrapper.onError (package:dio/src/interceptor.dart:125:22)
E/flutter (12258): #4      DioMixin._request._errorInterceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:868:34)
E/flutter (12258): #5      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1121:22)
E/flutter (12258): #6      DioMixin._request._errorInterceptorWrapper.<anonymous closure> (package:dio/src/dio.dart:866:16)
E/flutter (12258): #7      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter (12258): #8      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (12258): #9      _FutureListener.handleError (dart:async/future_impl.dart:160:20)
E/flutter (12258): #10     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
E/flutter (12258): #11     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
E/flutter (12258): #12     Future._completeError (dart:async/future_impl.dart:537:5)
E/flutter (12258): #13     _SyncCompleter._completeError (dart:async/future_impl.dart:59:12)
E/flutter (12258): #14     _Completer.completeError (dart:async/future_impl.dart:31:5)
E/flutter (12258): #15     Future.any.onError (dart:async/future.dart:481:45)
E/flutter (12258): #16     _rootRunBinary (dart:async/zone.dart:1214:47)
E/flutter (12258): #17     _CustomZone.runBinary (dart:async/zone.dart:1107:19)
E/flutter (12258): #18     _FutureListener.handleError (dart:async/future_impl.dart:157:20)
E/flutter (12258): #19     Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
E/flutter (12258): #20     Future._propagateToListeners (dart:async/future_impl.dart:729:24)
E/flutter (12258): #21     Future._completeError (dart:async/future_impl.dart:537:5)
E/flutter (12258): #22     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
E/flutter (12258): #23     DioMixin._dispatchRequest (package:dio/src/dio.dart)
E/flutter (12258): <asynchronous suspension>
E/flutter (12258): #24     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
E/flutter (12258): #25     DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1121:22)
E/flutter (12258): #26     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
E/flutter (12258): #27     new Future.<anonymous closure> (dart:async/future.dart:175:37)
E/flutter (12258): #28     _rootRun (dart:async/zone.dart:1182:47)
E/flutter (12258): #29     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (12258): #30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (12258): #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (12258): #32     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (12258): #33     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (12258): #34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (12258): #35     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (12258): #36     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (12258): #37     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (12258): #38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)`

gz#8930

**Comment by shodgetts** [comment] 2021-01-27 21:53
Agent comment from Ryan Kavanaugh in <a href='https://getstream.zendesk.com/agent/tickets/8930'>Zendesk ticket #8930</a>:<br><br>Hi,

Thanks for reaching out! We will be in touch as soon as possible. Please feel free to let us know if you have any other questions in the meantime.

Best,
Ryan

**Comment by natchoz** [comment] 2021-01-28 19:14
I think I found bug inside `_tokenExpiredInterceptor,` when token is expired, `_ws.connectionStatus.removeListener(_connectionStatusListener);` cause the `wsConnectionStatus.value` still be `ConnectionStatus.connected` although `disconnect` gets called already so the next time when client tries to connect again then get error  Already connected and lost the connection.

So please fix this issue.
Thank you.

`Future<void> _tokenExpiredInterceptor(DioError err) async {
    final apiError = ApiError(
      err.response?.data,
      err.response?.statusCode,
    );

    if (apiError.code == _tokenExpiredErrorCode) {
      logger.info('token expired');

      if (tokenProvider != null) {
        httpClient.lock();
        final userId = state.user.id;

        **_ws.connectionStatus.removeListener(_connectionStatusListener);**
        _**wsConnectionStatus.value = ConnectionStatus.disconnected;**_

        await _disconnect();

        final newToken = await tokenProvider(userId);
        await Future.delayed(Duration(seconds: 4));
        token = newToken;`

**Comment by imtoori** [comment] 2021-01-29 08:06
Thanks @natchoz 
We'll fix it as soon as possible, thanks for reporting the bug and for the investigation

**Comment by imtoori** [comment] 2021-01-29 08:31
I was trying to reproduce the bug and I managed to, it turns out removing the listener was the cause of the bug.
A new version with the fix will be released soon.

**Comment by imtoori** [comment] 2021-01-29 09:47
@natchoz the latest version of the api client 0.2.24+2 contains the fix

you should be able to use it running 
`flutter clean`
`flutter pub upgrade`

Let me know if that works :)

**Comment by natchoz** [comment] 2021-01-30 16:30
> @natchoz the latest version of the api client 0.2.24+2 contains the fix
> 
> you should be able to use it running
> `flutter clean`
> `flutter pub upgrade`
> 
> Let me know if that works :)

Thank you so much I will test and let you know asap.

**Closed** 2021-02-02 16:12 UTC
