### ISSUE TITLE
Push notification not working

### ISSUE THREAD

**Issue by developerpaaji** [GetStream/stream-chat-flutter#878] opened 2022-01-27 12:26 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

package - 3.3.2

### What happened?

I have added firebase credentials in dashboard and also setup my device. I am receiving notification when sent from postman.
BUT when i send new message to other user then i dont get notification but i get background notification with data -

{sender: stream.chat, message_id: 65c9590f-4895-4986-9a36-93b7cefb19b0, id: 65c9590f-4895-4986-9a36-93b7cefb19b0, channel_type: subscription, type: message.new, channel_id: 280299ab-9d83-4a23-a17e-903b676da9f6, version: v2, cid: subscription:280299ab-9d83-4a23-a17e-903b676da9f6}

Have tried to change template too but notthing worked

FCM package - firebase_messaging 11.2.4

### Steps to reproduce

```bash
Send message to other user
Add callbacks to firebase
In onMessage - RemoteMessage will have notification = null
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment] 2022-01-31 14:58
hey @developerpaaji 
you can take a look at this, I think it could help you https://getstream.io/chat/docs/sdk/flutter/guides/adding_push_notifications/#saving-notification-messages-to-the-offline-storage
are you using the persistence package? I'd like to send you a snippet to help you

**Comment by 1AhmedYasser** [comment] 2022-02-01 12:13
@imtoori the problem is that on the new update v2 push, the notification is sent as a data notification with notification object as null , so its not displayed by the phone when the app is closed to display It to the users

**Comment by imtoori** [comment] 2022-02-02 09:24
@1AhmedYasser yeah that's why I'm telling @developerpaaji to take a look at that link
Basically, you need to query the message using the information you have in the data field and show the notification locally using the flutter_local_notifications package

**Comment by developerpaaji** [comment] 2022-02-02 11:39
@imtoori thanks for sharing the article. This can work in Android only because in iOS when we use firebase_messaging onBackgroundMessage is not called when app is killed. [https://github.com/FirebaseExtended/flutterfire/issues/5988]()

**Comment by imtoori** [comment] 2022-02-02 11:42
they officially support that https://firebase.flutter.dev/docs/messaging/usage
have you tried it?

**Comment by developerpaaji** [comment] 2022-02-02 11:45
Yeah I have tried and can confirm that in IOS onBackgroundMessage is not called for data notifications when app is killed.
This is according to their documentation
`On iOS, if the user swipes away the application from app Switcher, it must be manually reopened again for background messages to start working again.`

**Comment by developerpaaji** [comment] 2022-02-04 11:46
@imtoori Any updates?

**Comment by imtoori** [comment] 2022-02-04 15:28
hey @developerpaaji I'm working on this, I'll post an update soon

**Comment by geweald** [comment] 2022-02-06 12:15
Hey @imtoori same issue here, started when I migrated from v1 (worked fine without background message handling) to v2, when the app is in bg then setting the `onBackgroundMessage` make the notifications work, but when the app is not running/terminated then it doesn't so seems like maybe the stream server needs to add some properties to the payload (like described in the messaging docs [here](https://firebase.flutter.dev/docs/messaging/usage/#low-priority-messages))

Looking forward for updates, thanks in advance

**Comment by kightsonsanom** [comment] 2022-02-18 07:01
@imtoori I've just spent a couple of hours trying to figure out why I am not receiving push notifications on any device. 


- I did everything from the [push overieview](https://getstream.io/chat/docs/flutter-dart/push_introduction/?language=dart) section,
- I have checked everything from the [most common issues and FAQ section](https://getstream.io/chat/docs/flutter-dart/push_-_common_issues_and_faq/?language=dart)
- I have also followed through the [push notification guide](https://getstream.io/chat/docs/sdk/flutter/guides/adding_push_notifications/). This is a bit confusing because the setup here is not updated - refers to v1 notifications which are marked as LEGACY in red on the chat dashboard,
- I've tried to run the code from the sample [chat push test repo](https://github.com/GetStream/chat-push-test). The sample uses too old firebase_messaging version and doesn't compile.

Turns out I did everything right and finally I found this issue and I learned that in order for pushes to work at all I need to follow [saving notifications to local storage](https://getstream.io/chat/docs/sdk/flutter/guides/adding_push_notifications/#saving-notification-messages-to-the-offline-storage) section which is located at the very bottom of non-updated part of the documentation in order for pushes to be working at all. The documentation should definitely be updated and include such information at the very top.

Can you confirm that using [stream_chat_persistence](https://pub.dev/packages/stream_chat_persistence) and [flutter local notifications](https://pub.dev/packages/flutter_local_notifications) is currently the only way to receive a push? This adds a lot of setup and complexity.

**Comment by 1AhmedYasser** [comment] 2022-02-18 14:36
@kightsonsanom so by doing this, you managed to get the notifications working even if the app is closed ?

**Comment by ghunkins** [comment] 2022-02-27 20:38
I faced all of the above issues. I ended up just switching over to using my own notifications using the webhooks feature.

**Comment by imtoori** [comment] 2022-03-09 10:52
Sorry about the delay, we're working on defining a good push v2 implementation for flutter and publish a guide.
I hope to get this done as soon as possible.

**Comment by imtoori** [comment] 2022-04-11 10:51
Hi we just released a new guide on v2 push notifications and Flutter

**Comment by imtoori** [comment] 2022-04-11 10:51
https://getstream.zendesk.com/agent/tickets/18925

**Comment by imtoori** [comment] 2022-04-11 10:51
https://getstream.io/chat/docs/sdk/flutter/guides/adding_push_notifications_v2/

**Closed by imtoori** 2022-04-11 10:51 UTC
Labels: bug
