### ISSUE TITLE
Crash when tapping on the attachment button.

### ISSUE THREAD

**Issue by duc-ios** [GetStream/stream-chat-flutter#1615] opened 2023-06-16 18:18 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter - 6.3.0

### What happened?

Crash when tapping on the attachment button.

### Steps to reproduce

```bash
1. Open the example app in stream_chat_flutter folder
2. Open lib/main.dart
3. Wrap the MaterialApp with another MaterialApp
4. Run the app
5. Navigate into any chat
6. Tap the attachment button
7. App crashes
```

### Supporting info to reproduce

```dart
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MaterialApp(
        debugShowCheckedModeBanner: false,
        theme: ThemeData.light(),
        darkTheme: ThemeData.dark(),
        // themeMode: ThemeMode.dark,
        supportedLocales: const [
          Locale('en'),
          Locale('hi'),
          Locale('fr'),
          Locale('it'),
          Locale('es'),
        ],
        localizationsDelegates: GlobalStreamChatLocalizations.delegates,
        builder: (context, widget) => StreamChat(
          client: client,
          child: widget,
        ),
        home: StreamChannel(
          channel: channel,
          child: const ResponsiveChat(),
        ),
      ),
    );
  }
```

### Relevant log output

```shell
════════ Exception caught by widgets library ═══════════════════════════════════
You must have a StreamChatTheme widget at the top of your widget tree
'package:stream_chat_flutter/src/theme/stream_chat_theme.dart':
stream_chat_theme.dart:1
Failed assertion: line 27 pos 7: 'streamChatTheme != null'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment] 2023-06-16 18:40
Duplicate of https://github.com/GetStream/stream-chat-flutter/issues/1429.

Hey @duc-ios, any particular reason you are using two MaterialApp ?

**Comment by duc-ios** [comment] 2023-06-16 18:44
@xsahil03x I have a big main app with multiple modules which are also flutter projects from different developers. StreamChat is just a module in that app.

**Comment by xsahil03x** [comment] 2023-06-16 18:47
I am not able to reproduce the issue with the code sample you provided, can you also share the structure you have at your end?

**Closed** 2023-06-16 23:48 UTC
Labels: bug
