### ISSUE TITLE
Playback Discrepancy: Video Concludes Prematurely Compared to Scrubber Position

### ISSUE THREAD

**Issue by juanleondev** [GetStream/stream-chat-flutter#1845] opened 2024-02-08 12:26 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

7.0.1

### What happened?

The player playback isn't synchronized with the actual time; the video concludes before the scrubber reaches the end, leaving it at the halfway mark when the video ends.

Steps to repro:

### Steps to reproduce

```bash
1. Go to messages

2. Shoot a video and send it

3. Allow the upload to complete

4. Go to the recipient inbox

5. Watch the video

6. See the scrubber time is incorrect
```

### Supporting info to reproduce

```
StreamMessageListView(
    dateDividerBuilder: (date) {
      return _DateDivider(dateTime: date);
    },
    messageBuilder:
        (context, details, messageList, defaultMessageWidget) =>
            defaultMessageWidget.copyWith(
      attachmentPadding: EdgeInsets.zero,
      borderSide: BorderSide.none,
      bottomRowBuilderWithDefaultWidget: (_, __, bottomRow) {
        return bottomRow.copyWith(
          showSendingIndicator: true,
          showTimeStamp: true,
          showUsername: false,
        );
      },
      messageTheme: details.isMyMessage
          ? defaultMessageWidget.messageTheme.copyWith(
              messageBackgroundColor: QTColors.primary80,
            )
          : defaultMessageWidget.messageTheme.copyWith(
              messageBackgroundColor: QTColors.primary20,
            ),
      onReplyTap: (message) {
        messageInputController.quotedMessage = message;
      },
      showReplyMessage: true,
      showUserAvatar:
          details.isMyMessage ? DisplayWidget.gone : DisplayWidget.show,
      userAvatarBuilder: (context, user) {
        return Avatar(
          avatarUrl: recipient.avatarPhoto.smallImagePath,
          initials: recipient.initials,
          radius: 24,
        );
      },
      showPinButton: false,
    ),
    showFloatingDateDivider: false,
    unreadMessagesSeparatorBuilder: _buildUnreadMessagesSeparator,
  ),
```

### Flutter analyze output

```shell
Analyzing queerie-app...                                                
No issues found! (ran in 11.0s)
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.16.4, on macOS 14.1.1 23B81 darwin-arm64, locale en-PE)
    • Flutter version 3.16.4 on channel stable at /Users/jjleoncamilo/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 2e9cb0aa71 (8 weeks ago), 2023-12-11 14:35:13 -0700
    • Engine revision 54a7145303
    • Dart version 3.2.3
    • DevTools version 2.28.4

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/jjleoncamilo/Library/Android/sdk
    • Platform android-34, build-tools 33.0.2
    • ANDROID_HOME = /Users/jjleoncamilo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.85.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.80.0

[✓] Connected device (5 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • Juan Jose’s iPhone (mobile) • 00008120-000C591C0113C01E            • ios            • iOS 17.2.1 21C66
    • iPhone 15 Pro Max (mobile)  • 4880999B-16D8-4EE7-AB0B-B16A52B5E3BA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-17-0 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 14.1.1 23B81 darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 121.0.6167.160

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by juanleondev** [comment] 2024-02-08 12:28
Video demo of the issue
https://github.com/GetStream/stream-chat-flutter/assets/8674244/cd80604e-b2fd-4e25-bad4-ead5926ce1d2

**Comment by deven98** [comment] 2024-07-22 15:46
Closing this for now as I can't reproduce this. Please feel free to reopen with more details if you are still facing it.

**Closed by deven98** 2024-07-22 15:46 UTC
Labels: bug, waiting for customer response
