### ISSUE TITLE
Using a GestureDetector in actions of StreamMessageInput causes text input to reset whenever you start typing

### ISSUE THREAD

**Issue by edeetee** [GetStream/stream-chat-flutter#1723] opened 2023-09-02 01:41 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

Web

### What version are you using?

6.9.0

### What happened?

If I have the reproduced widget as an action of the StreamMessageInput, whenever I start typing, it deletes the first character typed. 

I was initially trying to make a custom audio record widget, but the tutorials I came across seemed to cause a weird issue with the text input. I have tested the problem and seem to have gotten it down to the smallest reproducible elements.

### Steps to reproduce

```bash
1. Add an action widget with a Gesture detector and some size
2. Type one character in the message text input
3. The character disappears
4. If you type fast enough, the characters will stick around.
```

## StreamMessageInput
```dart
 StreamMessageInput(
  actions: [TestActionWidget()],
),
```

## Action widget
```dart
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class TestActionWidget extends StatelessWidget {
  const TestActionWidget({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
        onTap: () {},
        child: const SizedBox(
          width: 20,
          height: 20,
        ));
  }
}
```

## Thoughts
I think it's probably resetting the text state somewhere. It is very weird that the GestureDetector/InkWell is causing it, but it wouldn't trigger if it was just a SizedBox.

### Relevant log output

```shell
No errors logged!
```

### Flutter analyze output

```shell
No errors
```

### Flutter doctor output

```shell
➜ flutter doctor -v              
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.4.1 22F82
    darwin-arm64, locale en-NZ)
    • Flutter version 3.13.1 on channel stable at
      /Users/edwardtaylor/opt/flutter
    • Upstream repository
      https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (10 days ago), 2023-08-22
      21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at /Users/edwardtaylor/Library/Android/sdk
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)

[✓] IntelliJ IDEA Community Edition (version 2022.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.4.1 22F82 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by edeetee** [comment] 2023-09-02 01:43
I managed to work around this issue by setting 
```
enableActionAnimation: false
```
It would be nice to have the maximised space when the user is typing, but it's not the end of the world!

**Comment by xsahil03x** [comment] 2023-09-04 12:23
@edeetee can you also share a small video of the issue and what exactly you want it to behave? Thanks

**Comment by edeetee** [comment] 2023-09-04 22:19
# Recording
Here is the screen recording. The only input I'm doing is typing a single character into the message input area - the character 'a'. As you can see, it immediately disappears whenever I type it.

https://github.com/GetStream/stream-chat-flutter/assets/7484745/f04985ad-1896-47d2-a477-fd115c9b0563

# Expected behaviour
I expect the character a I type to stay around and for the actions animation to stay expanded

**Comment by xsahil03x** [comment] 2023-09-06 14:28
Hey @edeetee, I am unable to reproduce this at my end. Can you try to reproduce it in our [example](https://github.com/GetStream/stream-chat-flutter/tree/develop/packages/stream_chat_flutter/example) app? Thanks.

https://github.com/GetStream/stream-chat-flutter/assets/25670178/6970b837-6ce7-4b55-af21-1799aaf80430

**Comment by xsahil03x** [comment] 2023-09-07 12:22
@edeetee I am closing this issue as can't repro. We can always re-open once we have repro steps.

**Closed by xsahil03x** 2023-09-07 12:22 UTC
Labels: waiting for customer response
