### ISSUE TITLE
Version issues 7.2  'A value of type 'Stream<List<ConnectivityResult>>' can't be assigned to a variable of type 'Stream<ConnectivityResult>?'

### ISSUE THREAD

**Issue by CalHoll** [GetStream/stream-chat-flutter#1893] opened 2024-04-08 06:21 UTC
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

Android

### What version are you using?

For stream:
stream_chat_flutter: 7.2.0
stream_chat_persistence: 7.2.0
  
For Flutter:
Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (11 days ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1

For other relevant versions from settings.gradle:
```
    id "dev.flutter.flutter-plugin-loader" version "1.0.0"
    id "com.android.application" version "7.4.1" apply false
    id "org.jetbrains.kotlin.android" version "1.7.10" apply false
    id "com.google.gms.google-services" version "4.4.1" apply false
    id "com.google.firebase.crashlytics" version "2.9.9" apply false
```

### What happened?

I'm trying to bump versions of flutter and deps, things seem to be compatible with pub install - but when trying to run the app the errors in the included logs show up.

### Steps to reproduce

```bash
I've been trying to upgrade versions of flutter and gradle, the other v7 versions of stream_chat also have issues that seem to be resolved in 7.2 related to `photo_manager` and 

I assume the steps to reproduce are basically:
1. use my versions
2. run `flutter pub run`
```

### Relevant log output

```shell
../../.pub-cache/hosted/pub.dev/stream_chat_flutter_core-7.2.0/lib/src/stream_chat_core.dart:127:45: Error: A value of type 'Stream<List<ConnectivityResult>>' can't be assigned to a variable of type 'Stream<ConnectivityResult>?'.
 - 'Stream' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'ConnectivityResult' is from 'package:connectivity_plus_platform_interface/src/enums.dart' ('../../.pub-cache/hosted/pub.dev/connectivity_plus_platform_interface-2.0.0/lib/src/enums.dart').
      connectivityStream ??= Connectivity().onConnectivityChanged;
                                            ^
../../.pub-cache/hosted/pub.dev/stream_chat_flutter_core-7.2.0/lib/src/stream_chat_core.dart:129:30: Error: Method 'distinct' cannot be called on 'Stream<ConnectivityResult>?' because it is potentially null.
 - 'Stream' is from 'dart:async'.
 - 'ConnectivityResult' is from 'package:connectivity_plus_platform_interface/src/enums.dart' ('../../.pub-cache/hosted/pub.dev/connectivity_plus_platform_interface-2.0.0/lib/src/enums.dart').
Try calling using ?. instead.
          connectivityStream.distinct().listen((result) {
                             ^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/opt/homebrew/Caskroom/flutter/3.7.7/flutter/bin/flutter'' finished with non-zero exit value 1
```
```


### Flutter analyze output

```shell
All is good except a bunch of `textScaleFactor` deprecation warnings I haven't dealt with yet
```

### Flutter doctor output

```shell
all green
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andrewkimjoseph** [comment] 2024-04-08 08:17
Same issue.

**Comment by esarbanis** [comment] 2024-04-09 07:52
Hey everyone, sorry for this. There was a major update that was merged from dependabot, for `connectivity_plus`, that contained this breaking change. The reason why it was not detected during our regression testing was because of an earlier version was locked in our `pubspec.lock` file, so this breaking change passed through the cracks.

We have released `7.2.0-hotfix.1` version where we revert this change. We will include it in our upcoming beta release.

**Closed by esarbanis** 2024-04-09 07:52 UTC
Labels: bug

**Comment by zionnite** [comment] 2024-04-19 23:15
what can be done now, i'm still having this issues

**Comment by seborys40** [comment] 2024-04-20 17:39
Has anyone tried the hotfix? It still fails for me

**Comment by zionnite** [comment] 2024-04-20 19:19
hello @esarbanis,
even on the beta release, the `7.2.0-hotfix.1` it's not working

please, what can be done?, I need to package my app for **Stores** deployment but this is getting me delayed...

**Comment by zionnite** [comment] 2024-04-20 23:38
please, i need support for this, `hotfix` its not hot anymore and its not fix anything

**Comment by thompy02** [comment] 2024-04-22 20:05
Just finding this thread after running into the same issue myself. Was pretty excited to use getstream for my app but this really took the wind out of my sails. Any solutions yet?

**Comment by seborys40** [comment] 2024-04-24 02:22
downgrade to a previous version where the problem doesn't exist.

**Comment by zionnite** [comment] 2024-04-24 04:37
Have downloaded into many versions, issues persist

**Comment by seborys40** [comment] 2024-04-24 14:34
I still have to look further but make sure when you downgrade your package
manager is not caching the previous package

**Comment by zionnite** [comment] 2024-04-24 15:16
This I have done too,
But issue still persists

**Comment by wenchenglai** [comment] 2024-04-25 07:02
Just to chime in that I also have the same issue and I cannot deploy my app anymore due to this new bug.

**Comment by esarbanis** [comment] 2024-04-25 08:31
HI all, sorry for all this mess.

Just to clarify, `v7.2.0-hotfix.1` will work with `connectivity_plus: < 6.0.0`, for the reason I explained in my above comment. I will try to release a new beta with `connectivity_plus: > 6.0.0`, but the breaking change it introduced will need a full regression test from our side, so it might take a while. 

I suggest you downgrade `connectivity_plus` to `< 6.0.0` if you want a quick workaround.

**Comment by zionnite** [comment] 2024-04-26 08:33
hello @esarbanis 
i'm still getting this error after downgrading to connectivity_plus to v6.0.0
<img width="1440" alt="Screenshot 2024-04-26 at 09 31 12" src="https://github.com/GetStream/stream-chat-flutter/assets/10984801/f0bbad2a-dceb-4354-9254-4ac579892de6">

**Comment by zionnite** [comment] 2024-04-26 08:33
Is anyone able to resolve this?
please indicate...

**Comment by esarbanis** [comment] 2024-04-26 08:36
Hey @zionnite  in `connectivity_plus: < 6.0.0` version `6.0.0` is excluded, please use any `5.x.x` version

**Comment by zionnite** [comment] 2024-04-26 09:22
please, what do you think i should do
thanks.

**Comment by zionnite** [comment] 2024-04-26 09:54
Hello, thanks @esarbanis, for now we just wait till the next update is release,

we need Livekit in our project which is the most important feature in our MVP.

@esarbanis , thanks for always responding...

**Comment by flodaniel** [comment] 2024-04-29 12:33
@esarbanis when can we expect an updated package? The breaking change is minimal and we require this upgraded dependency due to some other dependencies, which we need to update to comply with the new iOS privacy manifest requirements.

**Comment by seborys40** [comment] 2024-04-30 00:40
set the following and you will be able to deploy

```
  stream_chat_flutter: 7.1.0
  connectivity_plus: 5.0.2
  ```

**Comment by JohnCoppa** [comment] 2024-04-30 18:33
A quick note that helped me when rolling back, is to notice that if you already installed 7.2.0, there's a dependency on stream_chat_flutter_core 7.2.0 that means you can't just change the version number of the main package, but need to 'flutter pub remove stream_chat_flutter' and then add the specific version in your pubspec.

**Comment by zionnite** [comment] 2024-04-30 20:03
I did this and it did not work for me

**Comment by JohnCoppa** [comment] 2024-04-30 20:31
I reverted to 7.1.0, but am now getting an error about dart_vlc, a dependency of stream_chat_flutter.

`.pub-cache/hosted/pub.dev/audio_video_progress_bar-0.11.0/lib/audio_video_progress_bar.dart:259:61: Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.`

**Comment by abeltilahunm** [comment] 2024-05-01 05:14
The @seborys40 worked for me.

**Comment by esarbanis** [comment] 2024-05-02 08:31
Hi everyone, again I apologise for all this. 

There is a [PR](https://github.com/GetStream/stream-chat-flutter/pull/1913) open towards our beta, once this is merged I will release a new beta and you can switch to that one if `connectivity_plus >= 6.0.0` is something integral in your app. But be warned that it is a beta release, so it might be unstable.

**Comment by danielkiing3** [comment] 2024-08-17 09:17
This same issue has yet to be resolved since first raised since April

Had to reverted to a older version `connectivity_plus: ^5.0.2` to get things to work
