### ISSUE TITLE
Unexpected strikethrough text on message bubble

### ISSUE THREAD

**Issue by APPXOTICA** [GetStream/stream-chat-flutter#1504] opened 2023-04-20 09:42 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter: ^4.2.0

### What happened?

Unexpected strikethrough text shown on message bubble.
This rarely happens but my client is not happy about it.

![IMG_7758F3E1D98D-1](https://user-images.githubusercontent.com/62071176/233325572-05ee1a73-2fd7-4514-9b0b-35067b90127e.jpeg)

### Steps to reproduce

```bash
It's not possible to reproduce this issue becuase it happens at random.
```

### Flutter doctor output

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.11, on macOS 13.1 22C65 darwin-arm64, locale en-VN)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.77.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment] 2023-04-26 12:42
Hey @APPXOTICA, can you tell me the language which is being used here? And also paste it so that we can test it on our end.

Thanks,
Sahil

**Comment by APPXOTICA** [comment] 2023-04-26 12:43
It's Korean.
아아갠춘 :) 한국은 비가 와요.
Thanks

**Comment by xsahil03x** [comment] 2023-04-26 12:45
Thanks, we will keep you posted.

**Comment by xsahil03x** [comment] 2023-05-01 12:10
Hey @APPXOTICA, we are not able to reproduce this on our end.

We internally uses [flutter_markdown](https://pub.dev/packages/flutter_markdown) to render the message text. So I advice you to make an issue on their repository.

You can check the implementation here:
https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat_flutter/lib/src/message_widget/message_text.dart

Thanks,
Sahil

**Comment by APPXOTICA** [comment] 2023-05-02 18:59
Sure, I will.
Thanks

**Comment by xsahil03x** [comment] 2023-05-02 21:41
Closing as not related to the SDK, Feel free to open again.

**Closed by xsahil03x** 2023-05-02 21:41 UTC
Labels: bug
