### ISSUE TITLE
Null - safety 

### ISSUE THREAD

**Issue by abraraltaf92** [GetStream/stream-chat-flutter#397] opened 2021-04-17 21:35 UTC
How much more time is needed to switch to null-safety? I am unable to integrate the stream_chat_flutter with my codebase(null-safety) .  When is it coming ?

**Comment by imtoori** [comment] 2021-04-18 07:41
Closing as a duplicate of #339
We're working on it and we'll have more news soon

**Closed by imtoori** 2021-04-18 07:41 UTC
Labels: enhancement
