### ISSUE TITLE
threadReplyCountText don't work in spanish language on iOS 17.0

### ISSUE THREAD

**Issue by juanan-onelife** [GetStream/stream-chat-flutter#1782] opened 2023-11-21 16:35 UTC
### Which packages are you using?

stream_chat_localizations

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter: 6.11.0
stream_chat_localizations: 5.11.0

### What happened?

With new iOS 17.0, the thread reply count text disappear if user use spanish language.

Checking the possible error, i see that if change to short text on the function threadReplyCountText works correctly.

![Simulator Screenshot - iPhone 15 - 2023-11-21 at 17 34 54](https://github.com/GetStream/stream-chat-flutter/assets/135533594/7283de2d-b2f5-4ff7-b849-9a071d5604a0)

![Simulator Screenshot - iPhone 15 - 2023-11-21 at 17 31 07](https://github.com/GetStream/stream-chat-flutter/assets/135533594/3f70343f-9eb4-4b55-a766-171235805b30)

### Steps to reproduce

```bash
1. Go to chat page
2. Reply message on thread page
```

### Supporting info to reproduce

https://github.com/GetStream/stream-chat-flutter/assets/135533594/505a5ff9-05bb-402d-b18e-9b0eae3f90a4

![Simulator Screenshot - iPhone 15 - 2023-11-21 at 17 10 23](https://github.com/GetStream/stream-chat-flutter/assets/135533594/db5c6eb5-391a-490c-81f0-c087557de0c4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment] 2023-11-23 15:33
Hi @juanan-onelife thank you for opening this issue with us.

I am very sorry, but I do not understand what kind of error you are having. Is it that the text is not showing some of the times, is it that it shows an incorrect text? 

>Checking the possible error, i see that if change to short text on the function threadReplyCountText works correctly.

What do you mean "change it to short text"?

**Comment by juanan-onelife** [comment] 2023-11-23 15:36
Hi @esarbanis, with the default translate text is not showing, but if a change the text with a one word, works correctly

**Comment by esarbanis** [comment] 2023-11-23 17:19
Thank you for the clarification :pray:

**Comment by deven98** [comment] 2024-06-12 13:06
Hey @juanan-onelife, apologies for the delays on this. 

After trying to reproduce this, I can see multiple threads show up fine:

<img width="236" alt="Screenshot 2024-06-12 at 3 04 33 PM" src="https://github.com/GetStream/stream-chat-flutter/assets/26357843/53fc4cb7-499d-4c81-b183-52e37bcd9230">

Are there any specific conditions under which this happens? Also, can you test this in the latest versions and let me know if it happens along with scenarios for reproduction of the error?

Please also check the logs once and send any error accompanying the building of the page. 

Thanks!

**Comment by deven98** [comment] 2024-06-17 09:46
Hey @juanan-onelife I'm closing this issue for now since I cannot replicate the same issue on the latest version.

However, feel free to reopen the issue if it reoccurs, and if you can, also provide any conditions that would help us reproduce the same. 

Thanks!

**Closed by deven98** 2024-06-17 09:46 UTC
Labels: bug, waiting for customer response
