### ISSUE TITLE
Message flickering as I scroll and changes background color

### ISSUE THREAD

**Issue by johnsonejezie** [GetStream/stream-chat-flutter#1330] opened 2022-09-12 20:53 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

4.5.0

### What happened?

My chat screen flickers and messages become not invisible. Tapping on a message returns the background color and cause more flicking

### Steps to reproduce

```bash
Open channel page
```

### Supporting info to reproduce

![IMG_6A98051A73B0-1](https://user-images.githubusercontent.com/8383735/189747500-2e3f9d9c-0bf7-45d2-90b0-ac5133bd4c06.jpeg)

https://user-images.githubusercontent.com/8383735/189750516-0649c689-6bc6-4f44-ae75-c1ce2cac06ef.mov

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imtoori** [comment] 2022-09-13 06:46
closing as duplicate of #1323

**Closed by imtoori** 2022-09-13 06:46 UTC
Labels: bug
