### ISSUE TITLE
Cannot compile with the dio: 5.2.0

### ISSUE THREAD

**Issue by yev-velizhenkov-adroiti** [GetStream/stream-chat-flutter#1597] opened 2023-06-08 06:16 UTC
### Which packages are you using?

stream_chat, stream_chat_flutter, stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, Android, Web, Windows, MacOS, Linux

### What version are you using?

stream_chat: ^6.2.0
stream_chat_flutter: ^6.2.0

### What happened?

 ../../../.pub-cache/hosted/pub.dev/stream_chat-6.2.0/lib/stream_chat.dart:5:1: Error: Error when reading '../../../.pub-cache/hosted/pub.dev/dio-5.2.0+1/lib/src/dio_error.dart': No such file or directory

### Steps to reproduce

```bash
1. have stream_chat: ^6.2.0 and dio: ^5.2.0
2. Compile
```

### Supporting info to reproduce

Because dio removed dio_error in 5.2.0 and stream_chat directly depends on dio_error.dart, compilation fails

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment] 2023-06-08 07:03
Closing as duplicate of https://github.com/GetStream/stream-chat-flutter/issues/1588 and fixed in https://github.com/GetStream/stream-chat-flutter/pull/1589

**Closed by xsahil03x** 2023-06-08 07:03 UTC
Labels: bug
