### ISSUE TITLE
Channel list does not sync new channels

### ISSUE THREAD

**Issue by Siqlain-Hanif** [GetStream/stream-chat-flutter#420] opened 2021-05-06 08:35 UTC
**Describe the bug**
So the use case we have is that some user follow a person on follow back we create a channel between them. We can go to that channel directly by using the cid, so that makes that the channel exists. But on channel list it does not show up. On restarting the app it does.

This is the snippet for the channel list if that helps.
![image](https://user-images.githubusercontent.com/53166182/117267719-01851080-ae70-11eb-8eae-6756cb525aeb.png)

**What package are you using? What version?** 
 2.0.0-nullsafety.2

**What platform is it about?**
- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**Comment by xsahil03x** [comment] 2021-05-06 08:39
Closing as duplicate of #413

**Closed by xsahil03x** 2021-05-06 08:39 UTC
Labels: bug, duplicate
