### ISSUE TITLE
AssertionError is thrown when rendering MessageListView with single custom message

### ISSUE THREAD

**Issue by filipesantoss** [GetStream/stream-chat-flutter#856] opened 2022-01-11 16:03 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

stream_chat_flutter 3.3.2

### What happened?

An `AssertionError` was thrown when [MessageListView](https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat_flutter/lib/src/message_list_view.dart) contained a single message rendered not using [MessageWidget](https://github.com/GetStream/stream-chat-flutter/blob/develop/packages/stream_chat_flutter/lib/src/message_widget.dart).

Expected no error to be thrown.

### Steps to reproduce

```bash
- Create a `messaging` channel with two members, e.g. `{ id: 'your.user.id' }` and `{ id: other.user.id }`
- Add a message to the channel created by the second user
- Launch the app
- Click the created channel in the list view
- Observe the app logs
```

### Supporting info to reproduce

```dart
import 'package:flutter/material.dart';
import 'package:stream_chat_flutter/stream_chat_flutter.dart' as stream;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final client = stream.StreamChatClient(
    'your.api.key', // replace by real value
    logLevel: stream.Level.INFO,
  );

  await client.connectUser(
    stream.User(id: 'your.user.id'), // replace by real value
    'your.token', // replace by real value
  );

  runApp(App(client: client));
}

class App extends StatelessWidget {
  final stream.StreamChatClient client;

  const App({
    Key? key,
    required this.client,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: const ChannelList(),
      builder: (_, widget) => stream.StreamChat(
        client: client,
        child: widget,
      ),
    );
  }
}

class ChannelList extends StatelessWidget {
  const ChannelList({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final userId = stream.StreamChat.of(context).currentUser!.id;

    return Scaffold(
      body: stream.ChannelsBloc(
        child: stream.ChannelListView(
          channelWidget: const Channel(),
          filter: stream.Filter.and([
            stream.Filter.equal('type', 'messaging'),
            stream.Filter.in_('members', [userId]),
          ]),
        ),
      ),
    );
  }
}

class Channel extends StatelessWidget {
  const Channel({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: stream.MessageListView(
        messageBuilder: (_, details, __, defaultWidget) =>
            details.message.user?.id == 'other.user.id' // replace by real value
                ? const Text('The other user sent a message.') // this causes an AssertionError
                : defaultWidget,
      ),
    );
  }
}
```

### Relevant log output

```shell
The following assertion was thrown during a task callback:
'package:flutter/src/rendering/layer.dart': Failed assertion: line 2280 pos 12: '_lastOffset != null': is not true.
package:flutter/…/rendering/layer.dart:1

When the exception was thrown, this was the stack
#2      LeaderLayer.applyTransform
package:flutter/…/rendering/layer.dart:2280
#3      _accumulateTransforms
package:visibility_detector/src/visibility_detector_layer.dart:37
#4      _localRectToGlobal
package:visibility_detector/src/visibility_detector_layer.dart:53
#5      VisibilityDetectorLayer._computeWidgetBounds
package:visibility_detector/src/visibility_detector_layer.dart:121
#6      VisibilityDetectorLayer._processCallbacks
package:visibility_detector/src/visibility_detector_layer.dart:227
#7      _TaskEntry.run.<anonymous closure>
package:flutter/…/scheduler/binding.dart:80
#8      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#9      _TaskEntry.run
package:flutter/…/scheduler/binding.dart:77
#10     SchedulerBinding.handleEventLoopCallback
package:flutter/…/scheduler/binding.dart:458
#11     SchedulerBinding._runTasks
package:flutter/…/scheduler/binding.dart:435
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

This exception was thrown in the context of a scheduler callback. When the scheduler callback was _registered_ (as opposed to when the exception was thrown), this was the stack
#0      new _TaskEntry.<anonymous closure>
package:flutter/…/scheduler/binding.dart:63
#1      new _TaskEntry
package:flutter/…/scheduler/binding.dart:65
#2      SchedulerBinding.scheduleTask
package:flutter/…/scheduler/binding.dart:399
#3      VisibilityDetectorLayer._handleTimer
package:visibility_detector/src/visibility_detector_layer.dart:194
```

### Flutter analyze output

```shell
No issues found! (ran in 3.6s)
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6 20G165 darwin-x64, locale en-GB)
    • Flutter version 2.8.1 at /usr/local/Caskroom/flutter/2.5.2/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 weeks ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/filipesantos/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

[✓] Connected device (2 available)
    • iPhone 12 Pro (mobile) • 78862E4E-873A-483D-A2EB-00AAB1073333 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-0 (simulator)
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 97.0.4692.71

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by avinath1998** [comment] 2022-01-20 07:17
Happens when on the last message of a MessageListView as well.
It typically occurs when you navigate away to an attachment and comeback to the MessageListView if and only if the last message sent is the Attachment you navigate to.

**Comment by bhayatus** [comment] 2022-01-22 19:00
Also getting this, but only sometimes. I can't seem to figure out the cause, but it happens even when I use the MessageListView ouf of the box.

**Comment by Freyien** [comment] 2022-01-25 14:42
I have one PageView and when I stay in the chat page and change to next or previous page the error happens.

Always happens.

**Comment by linhewinner** [comment] 2022-02-01 06:44
I am getting this 100% for a thread that has very few messages (so basically a new thread).

version 3.3.2

**Comment by flodaniel** [comment] 2022-02-04 12:53
We are also seeing this issue in the latest versions: 

>  stream_chat_flutter: ^3.4.0
>  stream_chat_localizations: ^2.1.0
>  stream_chat_persistence: ^3.1.0

It is enough to have an empty `MessageListView` on the page it seems like.

**Comment by AndreHaueisen** [comment] 2022-02-04 13:21
Same thing over here

**Comment by HayesGordon** [comment] 2022-02-15 09:47
Hi everyone. Seems like a really strange bug. I'll be taking a look at this soon and will update here as I make progress.

**Comment by HayesGordon** [comment] 2022-02-15 14:09
Seems like this is a Flutter issue, that has been fixed in https://github.com/flutter/flutter/pull/96144

If you would like to test if this resolves the problem for you, please switch to the `master` Flutter branch and test it out. It worked for me on iOS when doing a slow slide transition back to the previous screen.

We will keep this issue open until it lands on stable. If this is urgent for anyone we can investigate alternatives as an interim solution.

**Comment by imtoori** [comment] 2022-04-08 13:58
this pr removes the VisibilityDetector widget and should remove this error https://github.com/GetStream/stream-chat-flutter/pull/1065
You can find the fix in the next release we're pushing on Monday

**Closed by imtoori** 2022-04-08 13:58 UTC
Labels: bug
