### ISSUE TITLE
onBackgroundMessage push notification don't have payload

### ISSUE THREAD

**Issue by juanan-onelife** [GetStream/stream-chat-flutter#1779] opened 2023-11-17 10:48 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS

### What version are you using?

 stream_chat_flutter: 6.11.0
 firebase_core: 2.16.0
 firebase_messaging: 14.6.8
 flutter_local_notifications: 15.1.1

### What happened?

I try configure APN Template to send iOS notifications on my flutter app. All work correctly but when the app is in background, the push notification don't execute the FirebaseMessaging.onBackgroundMessage void in iOS device.  

If i try to get the active notifications  ** flutterLocalNotificationsPlugin.getActiveNotifications() **  the payload is empty and i can't cancel the notifications by id.

I have configured background properties in Xcode project.
 
![Captura de pantalla 2023-11-17 a las 11 42 26](https://github.com/GetStream/stream-chat-flutter/assets/135533594/406605e6-1477-43f5-907d-9fb9e1d14b6c)

Actually this is my APN template:

{
  "aps": {
    "alert": {
      "title" :"New message from {{ sender.name }}",
       "body": "{{ truncate message.text 2000 }} ",
    },
    "content-available" : 1,
    "badge": {{unread_count}},
    "apns-priority": 5
  },
  "data": {
    "sender": "stream.chat",
      "type": "message.new",
      "version": "v2",
      "id": "{{ message.id }}",
      "cid": "{{ channel.cid }}"
  }
}

Any suggestions on how I can fix this problem?

### Steps to reproduce

```bash
1. Execute iOS app in background
2. Send push notification
3. Open app and execute flutterLocalNotificationsPlugin.getActiveNotifications();
...
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.13.9, on macOS 14.1.1 23B81 darwin-arm64, locale es-ES)
    • Flutter version 3.13.9 on channel stable  
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d211f42860 (3 weeks ago), 2023-10-25 13:42:25 -0700
    • Engine revision 0545f8705d
    • Dart version 3.1.5
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK 
    • Platform android-33, build-tools 33.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by esarbanis** [comment] 2023-11-23 15:06
Duplicate of #1764 , let's track it there

**Closed by esarbanis** 2023-11-23 15:06 UTC
Labels: bug
