### ISSUE TITLE
Filtering does not work when querying channels

### ISSUE THREAD

**Issue by AlaaAbdelbaki** [GetStream/stream-chat-flutter#1887] opened 2024-03-28 07:45 UTC
### Which packages are you using?

stream_chat, stream_chat_flutter, stream_chat_flutter_core

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

7.1.0

### What happened?

Starting from today, whenever I try to query channels using a filter, the filter is always ignored, and the query function always returns the last 10 conversations.
<img width="442" alt="Screenshot 2024-03-28 at 10 08 18" src="https://github.com/GetStream/stream-chat-flutter/assets/44524232/4686bf12-f193-4776-b0b5-41d7ffa3be6d">
As you can see in the screenshot, we are trying to query the channels and filtering by a field in their extra data called company ID, for this example we are trying to query all the channels that have the value "enable" for the company ID field, but the client ignores the filter and queries the latest 10 channels. 

### Steps to reproduce

```bash
1. Try to query the available channels using a custom filter.
2. The returned channels are always the last 10 channels, and the filter used in the query function is ignored
```

### Flutter doctor output

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on Microsoft Windows [Version 10.0.22631.3296], locale en-GB)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.30)
    ✗ The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or reinstall Visual Studio.
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.87.2)
[✓] Connected device (3 available)
[✓] Network resources
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlaaAbdelbaki** [comment] 2024-03-28 09:09
We had to update the package internally in the [channels_api.dart file](https://github.com/GetStream/stream-chat-flutter/blob/master/packages/stream_chat/lib/src/core/api/channel_api.dart) we replaced the queryChannels method with this one
We replaced it from this: 
```dart
/// THIS IS THE OLD FUNCTION THAT'S CAUSING THE ERROR
/// Line 50
/// Requests channels with a given query from the API.
  Future<QueryChannelsResponse> queryChannels({
    Filter? filter,
    List<SortOption>? sort,
    int? memberLimit,
    int? messageLimit,
    bool state = true,
    bool watch = true,
    bool presence = false,
    PaginationParams paginationParams = const PaginationParams(),
  }) async {
    final response = await _client.get(
      '/channels',
      queryParameters: {
        'payload': jsonEncode({
          // default options
          'state': state,
          'watch': watch,
          'presence': presence,

          // passed options
          if (sort != null) 'sort': sort,
          if (filter != null) 'filter_conditions': filter,
          if (memberLimit != null) 'member_limit': memberLimit,
          if (messageLimit != null) 'message_limit': messageLimit,

          // pagination
          ...paginationParams.toJson(),
        }),
      },
    );
    return QueryChannelsResponse.fromJson(response.data);
  }
```

to this 

```dart
  /// THIS IS THE FIXED FUNCTION
  /// Line 50
  /// Requests channels with a given query from the API.
  Future<QueryChannelsResponse> queryChannels({
    Filter? filter,
    List<SortOption>? sort,
    int? memberLimit,
    int? messageLimit,
    bool state = true,
    bool watch = true,
    bool presence = false,
    PaginationParams paginationParams = const PaginationParams(),
  }) async {
    final response = await _client.post(
      '/channels',
      data: {
        // default options
        'state': state,
        'watch': watch,
        'presence': presence,

        // passed options
        if (sort != null) 'sort': sort,
        if (filter != null) 'filter_conditions': filter,
        if (memberLimit != null) 'member_limit': memberLimit,
        if (messageLimit != null) 'message_limit': messageLimit,

        // pagination
        ...paginationParams.toJson(),
      },
    );
    return QueryChannelsResponse.fromJson(response.data);
  }
```

**Comment by senkia24** [comment] 2024-03-28 09:10
Our production app is received wrong channels or sometimes error 403.

**Comment by nbourdin** [comment] 2024-03-28 09:30
@AlaaAbdelbaki So we need to wait for a new release with the update ?

**Comment by AlaaAbdelbaki** [comment] 2024-03-28 09:42
I'd say yes if you do not want to update the internal package yourself

**Comment by esarbanis** [comment] 2024-03-28 10:11
Hi everyone, I am checking with the team internally to see if there were any API changes. This code block haven't been touched for over [3 years now](https://github.com/GetStream/stream-chat-flutter/blame/master/packages/stream_chat/lib/src/core/api/channel_api.dart) ...

@AlaaAbdelbaki thank you for investigating. Can you please open a PR with this patch? Once I have confirmation internally from the team I will review and merge.

**Comment by tahaJemmali** [comment] 2024-03-28 10:20
Today, a backend update was rolled out, resulting in the disabling of the GET request used for querying channels. This has led to an issue where all users are now able to view every conversation due to the malfunctioning of the filtering feature. To address this, please restore the GET API request as an immediate corrective action. Following that, you can initiate the planning and development of a new release update to ensure a more comprehensive solution.

**Comment by nullpoint-dev** [comment] 2024-03-28 10:33
To add some extra info. 

Agreed that a backend update is likely causing these issues.

Out app uses the flutter UIKit and early hours of this morning all our users were unable to view any channels.

This is caused by all channel querys hitting a 403 stating that 'channels cannot be returned because you don't have acces to them'.

There has been not changes to any of the code associated with stream for months - on our backend or within the app.

Please can we have an update on when a rollback may occur?

**Comment by esarbanis** [comment] 2024-03-29 11:40
It was an issue with the latest deployment of our API, this should be fixed now. Thanks everyone for their quick response and feedback 🚀

**Closed by esarbanis** 2024-03-29 11:40 UTC
Labels: bug
