### ISSUE TITLE
Stream Incorrectly Uses Global Context

### ISSUE THREAD

**Issue by searchy2** [GetStream/stream-chat-flutter#386] opened 2021-04-07 00:46 UTC
**Is your feature request related to a problem? Please describe.**
Stream uses a mixture of widget context and global context. Some parts of the code incorrectly access the global context directly when it should access the widget context instead. In fact, I would strongly recommend using widget context for all context calls so the proper ancestor in the widget tree is accessed. 

**Issue:** with a mix of global and widget context calls, Stream precludes the following use cases:
- Showing chat in a dialog.
- Chat in a nested navigator tab.
- Chat in a separate module. 

Essentially, it becomes very difficult to include Stream as a module independently of the rest of the codebase. The requirement of a root level StreamChat widget is problematic for additional reasons:
- Incorrect theme for different StreamChat client instances.
- User authentication. StreamChat requires a user to be connected. How do you connect a user if the user has not logged in?
- Updating the StreamChat instance. If the user changes, because StreamChat is at the root of the widget tree, it's very difficult to update the client with a new user.

Generally, it's a bad practice and anti-pattern to require a root level widget as it is incompatible with many existing app architectures.  Instead, a global instance would be a better solution.

Let's take a look at a few examples to demonstrate the issue.
From the Stream code: 

message_list_view.dart Line 626
`backgroundColor: StreamChatTheme.of(context).colorTheme.white,`

message_input.dart Line 2130
`final streamChannel = StreamChannel.of(context);`

message_widget.dart Line 616
`StreamChat.of(context).user.id`

**Describe the solution you'd like**
Replace global context with widget context.

**Comment by imtoori** [comment] 2021-05-05 14:08
Hey @searchy2,
Our team tried reproducing the issue reported using a nested application structure and Provider.
Unfortunately, we were not able to reproduce this error using the structure described. As a result, we will be closing this issue but please feel free to reach out to our support channel if you are still experiencing this.
We also released a new null safe version of our SDK (Beta) so it may be worth trying again using this version.
Cheers,
Stream's Flutter Team

**Closed by imtoori** 2021-05-05 14:08 UTC
Labels: enhancement
