### ISSUE TITLE
Register Device in get stream server

### ISSUE THREAD

**Issue by jawad-arshad** [GetStream/stream-chat-flutter#1695] opened 2023-08-03 10:44 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: ^4.6.0

### What happened?

String token = (await FirebaseMessaging.instance.getToken())!;
 await chatClient.addDevice(token, PushProvider.firebase);

Your Add device method give me this execption, If you think about my token is not correct this is not an issue because my firebase push are working fine but according to your documentation this approach is not working see this error below and please I need solution as soon as possible we need push on chat thanks ! 
This is first time I'm adding device at stream server why he's saying token is not authorized and also I tried with getstream user's  token but still facing this issue: 
StreamChatNetworkError(code: 1000, message: Unauthorised, token not defined)

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
...
```

### Relevant log output

```shell
Request ║ POST
https://chat.stream-io-api.com/devices?api_key=e94eaf86ffjw
Unhandled Exception: StreamChatNetworkError(code: 1000, message: Unauthorised, token not defined)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment] 2023-08-04 09:53
@jawad-arshad can you share a sample code where I can reproduce it? And also can you try to reproduce it on our sample app?

https://github.com/GetStream/flutter-samples/blob/develop/packages/stream_chat_v1/lib/main.dart

**Comment by jawad-arshad** [comment] 2023-08-04 13:20
ok I will

**Comment by rlee1990** [comment] 2023-08-09 15:50
nevermind turns out it was a race issue where it was called before the current user was connected all the way. Added an await function and its working now.

**Comment by xsahil03x** [comment] 2023-08-11 09:41
@jawad-arshad  Closing as not able to reproduce.

**Closed by xsahil03x** 2023-08-11 09:41 UTC
Labels: bug, waiting for customer response
