### ISSUE TITLE
Users with emojis in their names have cut off text below their messages

### ISSUE THREAD

**Issue by jgadsby** [GetStream/stream-chat-flutter#495] opened 2021-06-23 17:36 UTC
**Describe the bug**
See title!

**What package are you using? What version?**
Latest nullsafety build

**What platform is it about?**
- [X] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS
- [ ] Linux

**To Reproduce**
1. Set a user's name in Stream as something like 'Bob 🎉'
2. Have them send a message to you in stream so that they are the 'other person'
3. See how their name under the message is cut off

**Screenshots**
![Screen Shot 2021-06-23 at 1 36 37 PM](https://user-images.githubusercontent.com/4282877/123143012-0efa5800-d428-11eb-9956-4d3ddadc8c33.png)

**Comment by deven98** [comment] 2021-06-24 08:45
Hey @jgadsby,

Emojis seem to move the baseline of Text in Flutter, 
I'm taking a look into what we can do to lock according to font or decrease size.

**Comment by deven98** [comment] 2021-06-24 08:47
Meanwhile, we have a `usernameBuilder` property in the latest `stream_chat_flutter` build which you can try out to build your own Text as well.

**Comment by imtoori** [comment] 2021-06-28 10:49
https://github.com/flutter/flutter/issues/28894
it's related to this issue
I'm trying to find a way to solve it

**Comment by imtoori** [comment] 2021-06-28 10:51
but the problem is that even if we make it not clipping the baseline will always be a bit below than it's supposed to be

**Comment by imtoori** [comment] 2021-06-28 10:52
and btw, this happens only on ios

**Comment by jgadsby** [comment] 2021-07-09 15:13
Using usernameBuilder and manually stripping out the emoji from the name helped mitigate the issue for me. Up to you whether you close this one :)

**Comment by imtoori** [comment] 2021-07-12 09:23
I'll close it just because it's not something we can really solve as it's a bug of the flutter sdk itself
thanks btw

**Closed by imtoori** 2021-07-12 09:23 UTC
Labels: bug, platform: ios
