### ISSUE TITLE
7.2.0-hotfix.1 not working

### ISSUE THREAD

**Issue by zionnite** [GetStream/stream-chat-flutter#1901] opened 2024-04-21 00:03 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

7.2.0-hotfix.1

### What happened?

I can't build app either in Android or iOS

### Steps to reproduce

```bash
1. Add package
2. Run Pub get
3. run the app on Android or ios
4. it crashes immediately
```

### Supporting info to reproduce

**iOS screenshot**
<img width="1440" alt="Screenshot 2024-04-21 at 00 56 03" src="https://github.com/GetStream/stream-chat-flutter/assets/10984801/61eacdc4-4baf-42eb-b7fe-837f2ac930dc">

**Android Screenshot**
<img width="1440" alt="Screenshot 2024-04-21 at 00 57 01" src="https://github.com/GetStream/stream-chat-flutter/assets/10984801/22bee37e-ea91-47fa-9b95-9e17a4cd82bf">

<img width="1440" alt="Screenshot 2024-04-21 at 00 57 11" src="https://github.com/GetStream/stream-chat-flutter/assets/10984801/4ed44b52-6b52-41c0-9e4f-7870643db2b9">

### Relevant log output

```shell
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...
Running Gradle task 'assembleDebug'...
You are applying Flutter's app_plugin_loader Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

You are applying Flutter's main Gradle plugin imperatively using the apply script method, which is deprecated and will be removed in a future release. Migrate to applying Gradle plugins with the declarative plugins block: https://flutter.dev/go/flutter-gradle-plugin-apply

../../.pub-cache/hosted/pub.dev/stream_chat_flutter_core-7.2.0/lib/src/stream_chat_core.dart:127:45: Error: A value of type 'Stream<List<ConnectivityResult>>' can't be assigned to a variable of type 'Stream<ConnectivityResult>?'.
 - 'Stream' is from 'dart:async'.
 - 'List' is from 'dart:core'.
 - 'ConnectivityResult' is from 'package:connectivity_plus_platform_interface/src/enums.dart' ('../../.pub-cache/hosted/pub.dev/connectivity_plus_platform_interface-2.0.0/lib/src/enums.dart').
      connectivityStream ??= Connectivity().onConnectivityChanged;
                                            ^
../../.pub-cache/hosted/pub.dev/stream_chat_flutter_core-7.2.0/lib/src/stream_chat_core.dart:129:30: Error: Method 'distinct' cannot be called on 'Stream<ConnectivityResult>?' because it is potentially null.
 - 'Stream' is from 'dart:async'.
 - 'ConnectivityResult' is from 'package:connectivity_plus_platform_interface/src/enums.dart' ('../../.pub-cache/hosted/pub.dev/connectivity_plus_platform_interface-2.0.0/lib/src/enums.dart').
Try calling using ?. instead.
          connectivityStream.distinct().listen((result) {
                             ^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/Users/zionnite/Developer/flutter/packages/flutter_tools/gradle/src/main/groovy/flutter.groovy' line: 1419

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/zionnite/Developer/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Error: Gradle task assembleDebug failed with exit code 1
```

### Flutter doctor output

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.2, on macOS 14.4.1 23E224 darwin-arm64,
    locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version
    34.0.0)
    ! Some Android licenses not accepted. To resolve this, run: flutter
      doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] IntelliJ IDEA Community Edition (version 2023.3.2)
[✓] VS Code (version 1.88.1)
[✓] Connected device (4 available)
[✓] Network resources

! Doctor found issues in 1 category.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thompy02** [comment] 2024-04-22 20:07
commenting on this issue to follow, having same issue. Considering reverting to v6.0

**Comment by zionnite** [comment] 2024-04-26 08:32
i'm still getting this error after downgrading to connectivity_plus to v6.0.0
<img width="1440" alt="Screenshot 2024-04-26 at 09 31 12" src="https://github.com/GetStream/stream-chat-flutter/assets/10984801/4a634ffd-24d3-4645-a964-d8c99144cd5d">

**Comment by esarbanis** [comment] 2024-04-26 08:40
Duplicate of #1893

**Closed by esarbanis** 2024-04-26 08:40 UTC
Labels: bug
