### ISSUE TITLE
Can't run the app after updating to version 6.5.0

### ISSUE THREAD

**Issue by adilsakout** [GetStream/stream-chat-flutter#1662] opened 2023-07-06 11:06 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

Version 6.5.0

### What happened?

After updating stream_chat_flutter to version 6.5.0, I get this error in both IOS and Android: 

../../.pub-cache/hosted/pub.dev/stream_chat_flutter-6.5.0/lib/src/attachment/handler/stream_attachment_handler_io.dart:34:32: Error: The method 'getSaveLocation' isn't defined for the class 'StreamAttachmentHandlerDesktop'.
 - 'StreamAttachmentHandlerDesktop' is from 'package:stream_chat_flutter/src/attachment/handler/stream_attachment_handler_io.dart' ('../../.pub-cache/hosted/pub.dev/stream_chat_flutter-6.5.0/lib/src/attachment/handler/stream_attachment_handler_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getSaveLocation'.
    final saveLocation = await getSaveLocation(suggestedName: data.fileName);

### Steps to reproduce

```bash
Just Update to version 6.5.0
```

### Relevant log output

```shell
Running Gradle task 'assembleDevDebug'...
../../.pub-cache/hosted/pub.dev/stream_chat_flutter-6.5.0/lib/src/attachment/handler/stream_attachment_handler_io.dart:34:32: Error: The method 'getSaveLocation' isn't defined for the class 'StreamAttachmentHandlerDesktop'.
 - 'StreamAttachmentHandlerDesktop' is from 'package:stream_chat_flutter/src/attachment/handler/stream_attachment_handler_io.dart' ('../../.pub-cache/hosted/pub.dev/stream_chat_flutter-6.5.0/lib/src/attachment/handler/stream_attachment_handler_io.dart').
Try correcting the name to the name of an existing method, or defining a method named 'getSaveLocation'.
    final saveLocation = await getSaveLocation(suggestedName: data.fileName);
                               ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception


FAILURE: Build failed with an exception.

* Where:
Script '/Users/adil/Documents/dev/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1201

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDevDebug'.
> Process 'command '/Users/adil/Documents/dev/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 51s
Exception: Gradle task assembleDevDebug failed with exit code 1
```

### Flutter doctor output

```shell
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E772610a darwin-arm64, locale en-DE)
    • Flutter version 3.10.5 on channel stable at /Users/adil/Documents/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 796c8ef792 (3 weeks ago), 2023-06-13 15:51:02 -0700
    • Engine revision 45f6e00911
    • Dart version 3.0.5
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/adil/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E222b
    • CocoaPods version 1.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.79.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.68.0

[✓] Connected device (4 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64  • Android 13 (API 33) (emulator)
    • iPhone 14 Pro (mobile)      • 9CAF0959-5688-4AED-A667-265DF7268164 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
    • macOS (desktop)             • macos                                • darwin-arm64   • macOS 13.3.1 22E772610a darwin-arm64
    • Chrome (web)                • chrome                               • web-javascript • Google Chrome 114.0.5735.198

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xsahil03x** [comment] 2023-07-06 11:36
Duplicate of https://github.com/GetStream/stream-chat-flutter/issues/1660

**Closed by xsahil03x** 2023-07-06 11:36 UTC
Labels: bug
