### ISSUE TITLE
"Save Image" attachment action broken

### ISSUE THREAD

**Issue by futebolbryant** [GetStream/stream-chat-flutter#1088] opened 2022-04-15 00:12 UTC
### Which packages are you using?

stream_chat_flutter

### On what platforms did you experience the issue?

iOS, Android

### What version are you using?

stream_chat_flutter: 3.6.0

### What happened?

I tried to save an image via attachment modal actions, but instead I got a square modal box with a really big negative number and no way to dismiss it on iOS.  On Android, you can swipe back to dismiss it.  On Android, the image is not saved.  on iOS, the image is saved.  Attached is a screen recording.  Note that I'm using the example code to reproduce, nothing custom.

https://user-images.githubusercontent.com/11775151/163495411-df3c617b-2d20-4c76-ae57-78acd4d3c2a5.mp4

### Steps to reproduce

```bash
1.  Send or receive an image in a chat channel
2.  Tap on the image
3.  Tap the options in the upper right hand corner of the screen
4.  Tap "Save Image"

Expected: After tapping "Save Image" I see a progress between 0 and 100%, and when it's done saving I can close the progress modal or it closes automatically.

Observed: 

IOS: A progress modal opens and I see a big negative number, seemingly the number of bytes of the file.  Once it's 'done' downloading, the modal remains and there is no way to dismiss it.  The image does seem to successfully save.

Android: Same as above except the image is not saved.
```

### Supporting info to reproduce

See attached screen recording above.

### Relevant log output

```shell
[no errors are logged]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ayush221b** [comment] 2022-04-15 04:34
Thank you for pointing this out. This was fixed in our newest v4 beta release. You can try that out here: https://pub.dev/packages/stream_chat_flutter/versions/4.0.0-beta.2

This issue has been mentioned before in #1071

**Closed by ayush221b** 2022-04-15 04:34 UTC
Labels: bug

**Comment by futebolbryant** [comment] 2022-04-15 04:40
So @ayush221b genuine question. If I want the most stable version of this library which should I choose? The beta? I didn’t see that previous ticket because I searched for open tickets. I’m trying to deploy a stable version of our app to production.

**Comment by imtoori** [comment] 2022-04-15 07:27
@futebolbryant the problem is that the fix required a breaking change to be fixed, so we decided to include it in the v4 release.
I think you could use v4, there should be no issue.
You can give it a try and let us know, we're gonna release a stable one later this month, but it's not gonna take more time.
