### ISSUE TITLE
Message read indicator broken in threads

### ISSUE THREAD

**Issue by geweald** [GetStream/stream-chat-flutter#1396] opened 2022-12-06 14:08 UTC
### Which packages are you using?

stream_chat_flutter, stream_chat_persistance

### On what platforms did you experience the issue?

iOS, Android, Web

### What version are you using?

Latest

### What happened?

The message read indicators (checkmarks) are working fine on the channel, but are broken on a thread. Sometimes it shows properly that message is read, sometimes it doesn't see that message was read. Especially visible when using a custom indicator (like user avatars who read the message - for that I'm using the logic that's similar to the one in `SendingIndicatorWrapper`)

### Steps to reproduce

```bash
1. Go to channel
2. Write a message and open a thread
3. Chat in the thread and see the read indicator not responding correctly
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by eli1stark** [comment] 2023-02-07 21:27
It's broken for me in **StreamChannelListTile** as well, sometimes it works sometimes it's not

**Comment by leandroBorgesFerreira** [comment] 2023-02-09 10:51
Hello. Sorry for the late reply, we were busy with other issues in the repository. I'll start taking a look at this one now.

**Comment by leandroBorgesFerreira** [comment] 2023-02-15 13:46
Hello @geweald. This problem needs some improvement for the backend. It is not possible to solve this in the SDK side, at the moment. A rework for threads is scheduled for the next quarter, then we will be able to fix the problem here. 

@eli1stark the problem you're referring to is a different one and will be handled. The PR is already open.

**Comment by csandovalgt** [comment] 2023-05-24 17:07
> Hello @geweald. This problem needs some improvement for the backend. It is not possible to solve this in the SDK side, at the moment. A rework for threads is scheduled for the next quarter, then we will be able to fix the problem here.
> 
> @eli1stark the problem you're referring to is a different one and will be handled. The PR is already open.

Hi @leandroBorgesFerreira, are there any updates regarding the improvements for threads?

**Comment by esarbanis** [comment] 2024-01-11 11:55
I cannot reproduce this in v7.01, I am closing it. Nevertheless if you are still experiencing this feel free to reopen

**Closed by esarbanis** 2024-01-11 11:55 UTC
Labels: bug, backend
