### ISSUE TITLE
Lighting Actions Pop-up does not close when navigating back to channels list

### ISSUE THREAD

**Issue by JayPerfetto** [GetStream/stream-chat-flutter#358] opened 2021-03-27 09:10 UTC
**Describe the bug**
When the lightning actions menu is open and you press the back button on a channel, it remains open and interferes with the channels list screen.

**What package are you using? What version?**
1.5.1

**To Reproduce**
Go to a channel, open the lightning actions, then press the back button without selecting an action.

**Expected behavior**
The menu should close and then Navigator.pop should be called

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/34031697/112716203-2b770a80-8ea2-11eb-8437-f10d7e1762f6.gif)

doctor output is unchanged from my prior reported issue

**Comment by deven98** [comment] 2021-03-30 05:41
Hey @JayPerfetto, thanks for letting us know.

I'm having a bit of a hard time reproducing this bug, so just a few questions:

1) Does this happen on all platforms (android + iOS)
2) Is the channel header all default or is the onBackPressed overridden?

**Comment by JayPerfetto** [comment] 2021-03-31 04:29
Interesting second question - I am overriding onBackPressed but my assumption was that was not an override, but rather a callback fired in addition to whatever logic was required for the core functionality of the page - I am closing the device keyboard onBack in my case but thats all. Would this be better suited in a WillPopScope callback?

I have only tested on iOS

**Comment by JayPerfetto** [comment] 2021-03-31 04:31
Tested reverting the onBackPressed override and that is indeed what is causing this bug. I would still say that is a bug though, as there is no way to manually dismiss the commands overlay from within any user-provided callback

**Comment by deven98** [comment] 2021-03-31 05:06
Glad it works, I will see if we can add a callback that gets called before the usual onBackPressed without overriding it or just have a way to close it.

**Comment by imtoori** [comment] 2021-04-01 10:59
hey @JayPerfetto I've tried overriding the onbackpressed callback and it's working fine for me
how are you overriding it?

**Comment by imtoori** [comment] 2021-04-01 11:03
also we already close the device keyboard when you tap on the back button

**Comment by JayPerfetto** [comment] 2021-04-01 16:03
```
onBackPressed: () {
             if (isKeyboardOpen(context)) {
               closeKeyboard(context);
             }
             model.goBack();
          },
```
```

  void goBack() {
    _navigationService.navigateWithTransition(
      HomeView(),
      transition: 'leftToRight',
    );
  }
```

**Comment by JayPerfetto** [comment] 2021-04-01 16:04
At this point i suppose im okay closing it since there's a workaround but I obviously captured the behavior in a live screen recording, so it happened somehow haha

**Comment by imtoori** [comment] 2021-04-01 19:07
I think it's happening because you're closing the keyboard and somehow that causes the bug
Closing the keyboard should be automatic, isn't it?

**Closed** 2021-04-09 08:42 UTC
Labels: bug, waiting for customer response
